name: Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore DeltaCore.CacheHelper/DeltaCore.CacheHelper.csproj

      - name: Build project
        run: dotnet build DeltaCore.CacheHelper/DeltaCore.CacheHelper.csproj --configuration Release --no-restore

      - name: Pack project
        run: dotnet pack DeltaCore.CacheHelper/DeltaCore.CacheHelper.csproj --configuration Release --no-build -o ./nupkgs

      - name: Push to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
